ALTER TABLE public.interview_sessions 
ADD COLUMN IF NOT EXISTS recording_url TEXT,
ADD COLUMN IF NOT EXISTS screen_recording_url TEXT,
ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS ended_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS duration INTEGER GENERATED ALWAYS AS (EXTRACT(EPOCH FROM (ended_at - started_at))::INTEGER) STORED;

ALTER TABLE public.interview_answers 
DROP COLUMN IF EXISTS recording_url,
DROP COLUMN IF EXISTS screen_recording_url,
DROP COLUMN IF EXISTS duration,
DROP COLUMN IF EXISTS started_at CASCADE,
DROP COLUMN IF EXISTS ended_at CASCADE;
